"""initial schema

Revision ID: 59d6e5ceb03a
Revises: 
Create Date: 2026-08-01 01:59:45.581450
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '59d6e5ceb03a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatches_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_dispatch_date'), ['dispatch_date'], unique=False)

    op.create_table('sheds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sheds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheds_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('looms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_number', sa.String(length=40), nullable=False),
    sa.Column('shed_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shed_id'], ['sheds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shed_id', 'loom_number', name='uq_loom_per_shed')
    )
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_looms_loom_number'), ['loom_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_looms_shed_id'), ['shed_id'], unique=False)

    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('shed_id', sa.Integer(), nullable=True),
    sa.Column('loom_id', sa.Integer(), nullable=True),
    sa.Column('rate_per_meter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shed_id'], ['sheds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_loom_id'), ['loom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_shed_id'), ['shed_id'], unique=False)

    op.create_table('production_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('DAY', 'NIGHT', name='shift', native_enum=False, length=8), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_meter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_date', 'shift', 'worker_id', 'loom_id', name='uq_production_worker_loom_date_shift')
    )
    with op.batch_alter_table('production_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_entries_loom_id'), ['loom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_entries_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_entries_worker_id'))
        batch_op.drop_index(batch_op.f('ix_production_entries_loom_id'))
        batch_op.drop_index(batch_op.f('ix_production_entries_entry_date'))

    op.drop_table('production_entries')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_shed_id'))
        batch_op.drop_index(batch_op.f('ix_workers_name'))
        batch_op.drop_index(batch_op.f('ix_workers_loom_id'))

    op.drop_table('workers')
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_looms_shed_id'))
        batch_op.drop_index(batch_op.f('ix_looms_loom_number'))

    op.drop_table('looms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sheds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheds_name'))

    op.drop_table('sheds')
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatches_dispatch_date'))
        batch_op.drop_index(batch_op.f('ix_dispatches_company_name'))

    op.drop_table('dispatches')
    # ### end Alembic commands ###
