"""pick types and unassigned workers

Revision ID: be63c4a0cbd5
Revises: 59d6e5ceb03a
Create Date: 2026-08-01 19:21:25.674760

Hand-adjusted from the autogenerated draft in two places:

1. ``pick_type`` is NOT NULL, so it is added with a server default to backfill
   existing rows, and the default is then dropped. Adding it bare would fail on
   any database that already holds production entries.
2. The dropped foreign key on ``workers.loom_id`` is not named explicitly.
   Alembic emitted ``drop_constraint(None, ...)``, which errors on PostgreSQL.
   Dropping the column removes its dependent FK on both PostgreSQL and SQLite
   (batch mode rebuilds the table), so the column drop stands on its own.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "be63c4a0cbd5"
down_revision: str | None = "59d6e5ceb03a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PICK_TYPE = sa.Enum(
    "P88X96", "P88X92", "P88X80", name="picktype", native_enum=False, length=12
)


def upgrade() -> None:
    with op.batch_alter_table("production_entries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pick_type",
                PICK_TYPE,
                nullable=False,
                server_default="P88X96",
            )
        )
    with op.batch_alter_table("production_entries", schema=None) as batch_op:
        batch_op.alter_column("pick_type", server_default=None)

    with op.batch_alter_table("workers", schema=None) as batch_op:
        batch_op.drop_index("ix_workers_loom_id")
        batch_op.drop_column("loom_id")


def downgrade() -> None:
    with op.batch_alter_table("workers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("loom_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_workers_loom_id_looms",
            "looms",
            ["loom_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index("ix_workers_loom_id", ["loom_id"], unique=False)

    with op.batch_alter_table("production_entries", schema=None) as batch_op:
        batch_op.drop_column("pick_type")
