"""record worker leave days

A day a worker did not work, stored rather than inferred from an empty
register — a blank day could equally be an absence or a sheet nobody filled
in, and that ambiguity is what gets argued about over a week's pay.

Revision ID: d8f4ee378546
Revises: c4f81b2d9a17
Create Date: 2026-08-22 12:35:17.214621
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd8f4ee378546'
down_revision: str | None = 'c4f81b2d9a17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'leave_date', name='uq_worker_leave_day')
    )
    with op.batch_alter_table('worker_leave', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_leave_leave_date'), ['leave_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_leave_worker_id'), ['worker_id'], unique=False)

    # Close this table to Supabase's REST API, exactly as migration
    # 9a1c7f3d5e20 did for the others. A new table in the public schema is
    # published by PostgREST and reachable with the publishable key unless
    # it is locked, and this one names who was absent and when.
    if op.get_bind().dialect.name == "postgresql":
        op.execute('ALTER TABLE "worker_leave" ENABLE ROW LEVEL SECURITY')
        for role in ("anon", "authenticated"):
            op.execute(
                sa.text(
                    f"""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
                            REVOKE ALL ON "worker_leave" FROM "{role}";
                        END IF;
                    END
                    $$;
                    """
                )
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_leave', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_leave_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_leave_leave_date'))

    op.drop_table('worker_leave')
    # ### end Alembic commands ###
